language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install: "pip install -r requirements.txt"
script: ./deploy.sh

env:
  secure: "dexNKrlvv5sNUr9oRfm6f/PIMCJgjWvsoJ+JAnFdhv8SDPqhzCHcDuo+YI/i6UZLA/DShAFtfxEAgYYVaXlyuRmgQld2x9sFw/FBr5nGnXVd/XbW68y2lBCN7t+LG/tiIIadKCFPugVFZUga4QPkguGdUriuFoCcUZCYZE7cESWTtghYB6vHiLP6oe34JuAiv3vkMb0KSz8VW2Ru5N4pJH+vpIvZm0A6uPbhL9qVcWHXjfMNC0xe6HtxczqYqxjioG79HUf/dFAdyNVNKz5ctwZ+xu7s1hr2aFel92X/3HBPkmj0PKGRnTl5+51Yx8hMm+2Um6WIiXvfaXUyhKCIGfKnSK9V4PWbpKEWy92Vjm4RhOe9chXBYKoplXUp+5mDXwLs18r7jxsw3m6hPrqpUQ6NHMLEU/lardcIYCIKczVdIw7INAkbZvxac40p6x/T2w/Q/mGK0/v8QuiSR1uG3kxWBcATq5h18qep85R/BCUpFwW/e7vg/8anRUYdSZphoFAxpLMj9pginSrkdZe1V7fS5AxuPM0HZ6tBtihfdSGyrIfpntk5StN1P5sZOO9TAfiMiBLU56YIlW8tQfhsqlfRCkB1QkHvdXmqroLWjG7wz23oOPm5BKLrarGGhTxH4VZ6TE05cwQr5Y2Hf5DBSryZJDCSXXDTDmXJG4N2CrQ="
